# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test": "00_core.ipynb",
         "leaky_loss": "00_core.ipynb",
         "unweighted_profit": "00_core.ipynb",
         "weighted_profit": "00_core.ipynb",
         "get_loss_fn": "00_core.ipynb",
         "noop": "01_models.ipynb",
         "shortcut": "01_models.ipynb",
         "Inception": "01_models.ipynb",
         "InceptionBlock": "01_models.ipynb",
         "InceptionTime": "01_models.ipynb",
         "InceptionTimeSgm": "01_models.ipynb",
         "plot_ts": "10_data.ipynb",
         "TSItem": "10_data.ipynb",
         "TSTensor": "10_data.ipynb",
         "TensorFloat": "10_data.ipynb",
         "random_curve_generator": "20_augmentations.ipynb",
         "random_cum_curve_generator": "20_augmentations.ipynb",
         "random_cum_noise_generator": "20_augmentations.ipynb",
         "magnoise": "20_augmentations.ipynb",
         "timewarp": "20_augmentations.ipynb",
         "magwarp": "20_augmentations.ipynb"}

modules = ["core.py",
           "models.py",
           "data.py",
           "augmentations.py"]

doc_url = "https://Takezo87.github.io/torchtools/"

git_url = "https://github.com/Takezo87/torchtools/tree/master/"

def custom_doc_links(name): return None