# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"test": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Takezo87.github.io/torchtools/"

git_url = "https://github.com/Takezo87/torchtools/tree/master/"

def custom_doc_links(name): return None
