# AUTOGENERATED! DO NOT EDIT! File to edit: 202_colab.ipynb (unless otherwise specified).

__all__ = ['ISCOLAB']

# Cell
ISCOLAB = 'google.colab' in sys.modules
if ISCOLAB:
    # uncomment for bleeding edge
    !pip install git+https://github.com/fastai/fastcore.git@master -q
    !pip install git+https://github.com/fastai/fastai2.git@master -q
    !pip install git+https://github.com/Takezo87/torchtools.git -q

    # uncomment for latest stable version

    # !pip install tsai -
# from tsai.all import *
# package_versions()
# hardware_details()

#export
from .core import *
from .data import *
from .models import *
from .datasets import *
from .augmentations import *
from .datablock import *
from .dataloader import *
from .experiments import *
from .configs import *

#export
import pandas as pd
import numpy as np
from fastai2.basics import *